/******************************************************************************/
/***         Generated by IBExpert 2016.10.30.1 07.11.2016 12:54:19         ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES CYRL;

SET CLIENTLIB 'C:\Program Files (x86)\Firebird\Firebird_3_0\fbclient.dll';

CREATE DATABASE 'D:\7 term\DataBases\PROVIDER.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET CYRL COLLATION CYRL;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_MAP_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_MAP_ID TO 1200000;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CONTRACTS (
    ID_CONTRACT      INTEGER NOT NULL,
    ID_SUBSCRIBER    INTEGER NOT NULL,
    "COUNT"          FLOAT,
    LOGIN            VARCHAR(12) NOT NULL,
    "PASSWORD"       VARCHAR(12) NOT NULL,
    ID_ADRESS        INTEGER NOT NULL,
    DATE_CONNECTION  DATE NOT NULL
);

CREATE TABLE FINANCE (
    ID_OPERATION    INTEGER NOT NULL,
    ID_CONTRACT     INTEGER NOT NULL,
    TYPE_OPERATION  BOOLEAN NOT NULL,
    "VALUE"         VARCHAR(10) NOT NULL,
    DATE_OPERATION  DATE NOT NULL
);

CREATE TABLE MAP (
    ID_ADRESS  INTEGER NOT NULL,
    STREET     VARCHAR(100) NOT NULL,
    HOUSE      INTEGER NOT NULL,
    FLAT       INTEGER NOT NULL,
    STATUS     BOOLEAN NOT NULL
);

CREATE TABLE OPTIONS (
    ID_OPTIONAL      INTEGER NOT NULL,
    NAME_OPT         VARCHAR(15) NOT NULL,
    DESCRIPTION_OPT  VARCHAR(400) NOT NULL,
    TERM_OPT         VARCHAR(10) NOT NULL,
    COST             DOUBLE PRECISION,
    NOTES_OPT        VARCHAR(400)
);

CREATE TABLE SERVICES (
    ID_SERVICE   INTEGER NOT NULL,
    ID_CONTRACT  INTEGER NOT NULL,
    ID_TARIFF    INTEGER NOT NULL,
    ID_OPTIONAL  INTEGER,
    DATE_OPEN    DATE NOT NULL,
    DATE_CLOSE   DATE
);

CREATE TABLE SUBSCRIBERS (
    ID_SUBSCRIBER  INTEGER NOT NULL,
    LAST_NAME      VARCHAR(30) NOT NULL,
    FIRST_NAME     VARCHAR(30) NOT NULL,
    PATRONYMIC     VARCHAR(30),
    PASSPORT       VARCHAR(15) NOT NULL,
    REGISTRATION   VARCHAR(500) NOT NULL,
    PHONE_NUMBER   VARCHAR(24) CHARACTER SET NONE NOT NULL
);

CREATE TABLE TARIFFS (
    ID_TARIFF           INTEGER NOT NULL,
    NAME_TARIFF         VARCHAR(12) NOT NULL,
    DESCRIPTION_TARIFF  VARCHAR(400) NOT NULL,
    TERM_TARIFF         INTEGER NOT NULL,
    COST_TARIFF         DOUBLE PRECISION NOT NULL,
    NOTE_TARIFF         VARCHAR(400)
);



/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE CONTRACTS ADD CONSTRAINT PK_CONTRACTS PRIMARY KEY (ID_CONTRACT);
ALTER TABLE MAP ADD CONSTRAINT PK_MAP PRIMARY KEY (ID_ADRESS);
ALTER TABLE OPTIONS ADD CONSTRAINT PK_OPTIONS PRIMARY KEY (ID_OPTIONAL);
ALTER TABLE SERVICES ADD CONSTRAINT PK_SERVICES PRIMARY KEY (ID_SERVICE);
ALTER TABLE SUBSCRIBERS ADD CONSTRAINT PK_SUBSCRIBERS PRIMARY KEY (ID_SUBSCRIBER);
ALTER TABLE TARIFFS ADD CONSTRAINT PK_TARIFFS PRIMARY KEY (ID_TARIFF);


/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE CONTRACTS ADD CONSTRAINT FK_CONTRACTS_1 FOREIGN KEY (ID_SUBSCRIBER) REFERENCES SUBSCRIBERS (ID_SUBSCRIBER);
ALTER TABLE CONTRACTS ADD CONSTRAINT FK_CONTRACTS_2 FOREIGN KEY (ID_ADRESS) REFERENCES MAP (ID_ADRESS);
ALTER TABLE FINANCE ADD CONSTRAINT FK_FINANCE_1 FOREIGN KEY (ID_CONTRACT) REFERENCES CONTRACTS (ID_CONTRACT);
ALTER TABLE SERVICES ADD CONSTRAINT FK_SERVICES_1 FOREIGN KEY (ID_CONTRACT) REFERENCES CONTRACTS (ID_CONTRACT);
ALTER TABLE SERVICES ADD CONSTRAINT FK_SERVICES_2 FOREIGN KEY (ID_OPTIONAL) REFERENCES OPTIONS (ID_OPTIONAL);
ALTER TABLE SERVICES ADD CONSTRAINT FK_SERVICES_3 FOREIGN KEY (ID_TARIFF) REFERENCES TARIFFS (ID_TARIFF);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: MAP_BI */
CREATE TRIGGER MAP_BI FOR MAP
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id_adress is null) then
    new.id_adress = gen_id(gen_map_id,1);
end
^
SET TERM ; ^

